title: My first blog on github
author: Sofia Romero
email: romero.sofia.be@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first blog and I look forward to creating more content
  once I learn the basics :)

# social links
github_username:  Sofia-Romero # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
